WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fddc9be00a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4d3c91d8cf8966ea4213528010254583/url
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fddc9be03a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4d3c91d8cf8966ea4213528010254583/url
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fddc9be04f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4d3c91d8cf8966ea4213528010254583/url
